name: ci
concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - v*.*.x
    tags:
      - v*.*.*
  pull_request:
    types: [opened, synchronize]
    branches:
      - '*'

jobs:
  cruby:
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.2", "2.3", "2.4", "2.5", "2.6", "2.7", "3.0", "3.1", "ruby-head", "truffleruby-head"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true
      - name: html5
        run: bundle exec rake
      - name: html4
        run: bundle exec rake
        env:
          LOOFAH_HTML4_MODE: "t"

  cruby-nokogiri-system-libraries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
      - name: Install nokogiri with system libraries
        run: |
          sudo apt install pkg-config libxml2-dev libxslt-dev
          bundle config set force_ruby_platform true
          bundle config build.nokogiri --enable-system-libraries
          bundle install
          bundle exec nokogiri -v
      - name: html5
        run: bundle exec rake
      - name: html4
        run: bundle exec rake
        env:
          LOOFAH_HTML4_MODE: "t"

  jruby:
    continue-on-error: true # nokogiri on jruby has different behavior
    strategy:
      fail-fast: false
      matrix:
        ruby: ["jruby-9.2", "jruby-9.3", "jruby-head"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true
      - run: bundle exec rake
